### PR TITLE
Updated Error log as warning.. Features/powerbiactions

### PR DESCRIPTION
**Pull request by nitin-AET-Tankers**
Check if the changes are okay or not?

### CODE REVIEW

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag Gateway changes are working; I just intended to update error as warning; and added error block when the entered gateway is not found. **Please review before merging**.

I will test the rest tomo, if latest version is published 👍

**Comment by maikvandergaag** [comment]
Beta should be their shortly

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag  Line328 of function New-DatasetRefresh there is a bracket missed that resulted in error after successful refresh. Am sorry if this was my merge issue -_-  Can you please correct this? Or shall I?

Is it okay if I include logs for all dataset? like each dataset- Parameter updated successfully for 'datasetName'

image

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag  Please hold.. I am making he change.. will push in sometime...

**Pull request merged**
