### PR TITLE
Addition of Variables to Release trigger

### PR DESCRIPTION
**Pull request by Smushatron**
Hey Maik,

clearly a first stab at this and not tested but i thought this would be a good starter for 10 of getting variables to be added to the JSON body to be passed when triggering Releases.

thanks

### CODE REVIEW

**Comment by maikvandergaag** [comment]
@Smushatron : thank you for the addition. Will test it as soon as possible. It has been a bit hectic over here.

**Comment by mjfara** [comment]
Any update on this? Desperately need variable functionality in this task.

**Comment by pbojanczyk** [comment]
Yes, any update on this?  PR looks pretty straight forward

**Comment by maikvandergaag** [comment]
@mjfara  and @pbojanczyk: Would one of you have time to test it when I publish a Beta release?

I have some personal things going on that leaves me not that much time and If i'm not mistaken the solution is not that straight forward as I have dealed with this problem before

**Comment by jorgemarti** [comment]
This would be really interesting also for me, if implemented.

**Comment by maikvandergaag** [comment]
Thanks for your submission but will close this for now as we have a new version and will incorporate it there

**Pull request closed without merging**
