### PR TITLE
Parameter changes added;

### PR DESCRIPTION
**Pull request by nitin-AET-Tankers**
Parameter changes added; but unable to restore DLL & XML files in powerbiactionsnew; due to the // present in the foldername.
Need @maikvandergaag 's help in 

1. Including an option to map the JSON config file to $configFilePath from the Build Artifact location to the DevOps task input
2. Generalizing take over dataset so that users can use that as a separate task
**New parameters-** $Environment, $configFilePath
**New Functions-** Update-PowerBIDatasetParameters; Update-PowerBIDatasetParameter; Get-PowerBiDataSetParameter; Take-PowerBIDataSetInGroup

### CODE REVIEW

**Comment by maikvandergaag** [comment]
@nitmatgeo, I have closed your pull request as I have added al the functionalities in the new extension. Version 4 of the extension is deprecated. I have supplied you with the beta version

**Comment by nitin-AET-Tankers** [comment]
image


Can you please help to check that?

**Comment by maikvandergaag** [comment]
Yes off course could you share some more information. Like the urls that are being called I can see it completely and the configuration of your task

**Comment by nitin-AET-Tankers** [comment]
> Yes off course could you share some more information. Like the urls that are being called I can see it completely and the configuration of your task
Please excuse me for masking few identifiers due to some internal policies :O
image
image

**Comment by maikvandergaag** [comment]
Hi, I have pushed a small change should be available in the beta wihtin 5 min

**Comment by nitin-AET-Tankers** [comment]
> Hi, I have pushed a small change should be available in the beta wihtin 5 min

Whats the taks id? 5.1.4 still resulting in same error
image


Please note: All parameters need not be a part of the Report; please refer to the logic I had incorporated in my pull request. I was updating parameters only after cross checking the presence of JSON Parameter & actual parameter used in Report.

**Comment by nitin-AET-Tankers** [comment]
> > Hi, I have pushed a small change should be available in the beta wihtin 5 min
> 
> Whats the taks id? 5.1.4 still resulting in same error
> 
> Please note: All parameters need not be a part of the Report; please refer to the logic I had incorporated in my pull request. I was updating parameters only **after cross checking the presence of JSON Parameter & actual parameter used in Report**.


$configFilePath & $Environment is now obsolete in the old copy I checked-in: 

Function Get-PowerBiDataSetParameter {
    Param(
        [parameter(Mandatory = $true)]$GroupPath,
        [parameter(Mandatory = $true)]$AccessToken,
        [parameter(Mandatory = $true)]$setId,
        [parameter(Mandatory = $true)]$Environment,
        [parameter(Mandatory = $true)]$configFilePath
    )
    
    $url = $powerbiUrl + "$GroupPath/datasets/$setId/parameters"
    $updateJSON = ""

    $config_PowerBI_JSON = Get-Content $configFilePath | ConvertFrom-Json
    $JSON_ParametersPBI = $config_PowerBI_JSON.Environment.$Environment

    $result = Invoke-API -Url $url -Method "Get" -AccessToken $AccessToken -Verbose
    $parameters = $result.value
	
    foreach ($parameter in $parameters) {
        $parameterName = $parameter.name
        if ($JSON_ParametersPBI.name -match $parameterName) {       
            $parameterValue = $JSON_ParametersPBI | Where-Object name -eq $parameterName
            $parameterValue = $parameterValue.newValue
            if ($updateJSON -eq "") {
                $updateJSON = "{
                                    'name': '$parameterName',
                                    'newValue': '$parameterValue'
                                }"
            }
            else {
                $updateJSON = $updateJSON + "," +
                "{
                        'name': '$parameterName',
                        'newValue': '$parameterValue'
                }"
            }
        }
    }

    if (!$updateJSON -eq "") {
        $updateJSON = "{ 
                            'updateDetails': [" + $updateJSON + "]
                       }"
    }
    return $updateJSON
}

**Comment by maikvandergaag** [comment]
Yes I can build that in if needed but could you first check with parameters that are in all the datasets? I have updated it again because there was a little issue in the json going to the api

It should be version 5.1.5

**Comment by nitin-AET-Tankers** [comment]
> Yes I can build that in if needed but could you first check with parameters that are in all the datasets? I have updated it again because there was a little issue in the json going to the api
> 
> It should be version 5.1.5

Cheers @maikvandergaag 
Its working, first 3 reports was published successfully. Other reports have issue due to other parameters. Please assist with requested changes as well.

In bulk publish mode, there maybe reports that do not have a parameter; hence the requested change is necessary :)

**Comment by nitin-AET-Tankers** [comment]
> Yes I can build that in if needed but could you first check with parameters that are in all the datasets? I have updated it again because there was a little issue in the json going to the api
> 
> It should be version 5.1.5

@maikvandergaag Can you please build that as well? The architecture in our project follows a deployment from Azure Repos, so usually it is like a bulk mode. Now every addition of parameter config, one has to edit the JSON in pipeline.

**Comment by nitin-AET-Tankers** [comment]
> Yes I can build that in if needed but could you first check with parameters that are in all the datasets? I have updated it again because there was a little issue in the json going to the api
> 
> It should be version 5.1.5

Please let me know if you need any help with testing for parameters; Also requesting to include the check for parameters as conveyed in other comments :) Thanks a lot @maikvandergaag

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag  Hope the merge request is helpful to you. Please refer #212
A request, please help to ensure the rollout ASAP, let me know if you need my help to expedite this.
After your recent changes, the code really looks so neat and organised ^_^

**Comment by maikvandergaag** [comment]
Will work on it today! Will ping you when ready

Groetjes,

Maik van der Gaag
________________________________
Van: nitin-AET-Tankers <notifications@github.com>
Verzonden: Wednesday, September 30, 2020 9:32:06 AM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Parameter changes added; (#209)


@maikvandergaag<https://github.com/maikvandergaag> Hope the merge request is helpful to you. Please refer #212<https://github.com/maikvandergaag/msft-extensions/pull/212>
A request, please help to ensure the rollout ASAP, let me know if you need my help to expedite this.
After your recent changes, the code really looks so neat and organised ^_^

**Comment by nitin-AET-Tankers** [comment]
> Will work on it today! Will ping you when ready Groetjes, Maik van der Gaag
> […](#)

Please let me know once deployed in Dev Task :) I hope I can reuse the already installed Dev Task..

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag  many thanks Maik 👍 Dev was successful in my case. 
Will the dataset refresh automatically after every publish? Any option to configure schedule refresh?

image

**Pull request closed without merging**
