### PR TITLE
Added support for setting dataset permissions

### PR DESCRIPTION
**Pull request by yorickbouma**
We automatically deploy Tabular Models as Datasets in Power BI. In order to be able to use these Datasets from Excel we need to set Permissions on the Dataset level. This change adds support to this lovely extension for setting these permissions.

image

### CODE REVIEW

**Comment by yorickbouma** [comment]
@maikvandergaag let me know if you have any questions about the change, any additional requirements or need help with testing.

**Comment by maikvandergaag** [comment]
Hi @yorickbouma thanks for the addition I will move it in the process will you be able to test it in the beta version. I can give you access to that one if needed.

**Comment by yorickbouma** [comment]
> Hi @yorickbouma thanks for the addition I will move it in the process will you be able to test it in the beta version. I can give you access to that one if needed.

Of course, just let me know how and when 😊

**Comment by yorickbouma** [comment]
> It is now being deployed as beta. What is your organization for azure devops that way I can openup the beta for you

BLINK-HNL

**Comment by maikvandergaag** [comment]
I have added the org to the beta. You can download the beta from here: https://marketplace.visualstudio.com/items?itemName=Development-vanderGaag.maikvandergaag-power-bi-actionsDev

**Comment by yorickbouma** [comment]
@maikvandergaag  Functionally it works well. However, the helper window could be better:

- I'll move the PrincipalType above Groups/Users input (makes more sense)
- It would be nice if the Groups/Users input hides based on the selected principal type. Do you know if something like this is supported? The documentation of visibleRule is quite lacking...
  - Action = AddUsers || (Action = SetDatasetPermissions && PrincipalType = User)
  - Action = AddUsers || Action = SetDatasetPermissions && PrincipalType = User

image

**Comment by maikvandergaag** [comment]
Oke, let me know when the change is in. Regarding the visibility as far as I know you can also use && or || in the rule in not use them together in the rule.

But you could try t.

**Comment by yorickbouma** [comment]
Ok lets see :) https://github.com/maikvandergaag/msft-extensions/pull/415

**Comment by maikvandergaag** [comment]
Merged the PR. Will let you know when it is in the Beta

**Comment by maikvandergaag** [comment]
fixed will not work. Received the following error will doing the deploy: Rule cannot contain both \'&&\' and \'||\' operators.

**Comment by yorickbouma** [comment]
That's a shame. I see three solutions:
- Create an "Identifiers" input that is visible in both cases (User/Group). Add in the information that object id's should be entered when principal type = Group and emails should be entered when principal type = User
- Add two new inputs for Groups/Users, but name them slightly different (DatasetPermissionsUsers, DatasetPermissionsGroupObjectIds) and use these only for this Action. The visible rule can then just be: Action = SetDatasetPermissions && PrincipalType = User
- Keep it as is was. So the Groups/Users will always both show and one of them has an unjustified asterisk 

What do you think?

**Comment by maikvandergaag** [comment]
I would use option two

**Comment by maikvandergaag** [comment]
The problems keep popping up as the extension is growing to large. I have things in mind of maybe cutting the extensions up in multiple extensions and with this implemented in that way it will be easier to do.

**Comment by yorickbouma** [comment]
@maikvandergaag it does not seem to trigger an update, also after uninstalling/installing I still see the previous task.json

image

**Comment by maikvandergaag** [comment]
Correct were some issues with the pull request that I have also missed. The new beta version just got published.

**Comment by yorickbouma** [comment]
Taks settings works now and it is also still functionally working
image

**Comment by maikvandergaag** [comment]
Great, it is now also deploying to production

**Pull request merged**
