### PR TITLE
add action BindToGateway

### PR DESCRIPTION
**Pull request by Shahyads**
to address #475

### CODE REVIEW

**Comment by maikvandergaag** [comment]
@Shahyads: Could you tell me how your part is different from the action: UpdateGateway?

**Comment by Shahyads** [comment]
> @Shahyads: Could you tell me how your part is different from the action: UpdateGateway?
@maikvandergaag 
The underlying REST API is different. 
It seems UpdateGateWay needs more privileged user account so that I'm getting the following error message.
`##[error]No gateway found! Ensure MasterAccount authentication is used and check if specified gateway 'Gateway_PROD' is valid and present`
The error is coming from the first line in Update-PowerBIDatasetDatasourcesInGroup when it calls Get-PowerBIGateways
The point is that If I can do something manually with an account without any permission issue then I should be able to do it through PowerBIActions pipeline tasks with the same account without any permission issue. right?

**Comment by maikvandergaag** [comment]
I see its is beign merged now. Will be released in Beta first could you try the beta version?

**Comment by Shahyads** [comment]
Thanks @maikvandergaag.
in our company the application teams doesnt have enough permission to be able to get gateways. That's why I had to write the new action to use less privileged REST APIs for binding to the gateway.
Thanks for merging my code. 
When are you going to release it? 

How can i get the beta version? You might need to share it with my azure devops org [ShahyadS](https://dev.azure.com/ShahyadS) right?

**Comment by Shahyads** [comment]
Hi @maikvandergaag 
It seems you've shared a wrong version.
image001
thanks

**Pull request merged**
