### PR TITLE
Fixed use case for UpdateAll = false and datasetName is specified

### PR DESCRIPTION
**Pull request by albertlinga**

### CODE REVIEW

**Comment by maikvandergaag** [comment]
I think we were both fixing the issue. It is already in Beta for testing. Do you have access?

**Comment by albertlinga** [comment]
I don't think I have access. And not sure how to use beta versions if you give me access.

**Comment by maikvandergaag** [comment]
if you give me your devops url. I will give you access it is just installing a extension.
for the rest it works the same

**Comment by albertlinga** [comment]
https://dev.azure.com/alinga-dev/

**Comment by maikvandergaag** [comment]
You can install it from this page: https://marketplace.visualstudio.com/items?itemName=Development-vanderGaag.maikvandergaag-power-bi-actionsDev

**Comment by albertlinga** [comment]
Thank you. How I wish the PowerBI rest api for the lists, e.g. /datasets, supports filter queries. Imagine if you have many datasets in a workspace and you have to loop on it just to find the matching name.

**Comment by maikvandergaag** [comment]
Yes, that would be great.

In the next couple of weeks I will be working on some enhancements to make it faster.


Met vriendelijke groet,

Maik van der Gaag

**Pull request closed without merging**
